# Generated by Django 4.2.1 on 2023-06-01 18:47

from django.db import migrations, models
import django.db.models.deletion
import fandangos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Médio'), ('GRANDE', 'Grande')], max_length=20)),
                ('data_doacao', models.DateField(auto_now_add=True)),
                ('data_retirada', models.DateField(validators=[fandangos.models.MinValueValidator])),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fandangos.doador')),
            ],
        ),
    ]
