# Generated by Django 4.2.1 on 2023-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fandangos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='doador',
            field=models.CharField(max_length=50),
        ),
    ]
